// Generated by CoffeeScript 1.4.0
(function() {

  $().ready(function() {
    module("Fibonacci generátor");
    test("0==0", function() {
      return equal(fibonacci(0), 0);
    });
    test("1==1", function() {
      return equal(fibonacci(1), 1);
    });
    test("2==1", function() {
      return equal(fibonacci(2), 1);
    });
    test("5==5", function() {
      return equal(fibonacci(5), 5);
    });
    return test("7==13", function() {
      return equal(fibonacci(7), 13);
    });
  });

}).call(this);
