// Generated by CoffeeScript 1.4.0
(function() {

  window.fibonacci = function(n) {
    var c, t, x, y;
    x = 0;
    y = 1;
    c = 0;
    t;

    while (c !== n) {
      t = x;
      x = y;
      y += t;
      c++;
    }
    return x;
  };

}).call(this);
