// Generated by CoffeeScript 1.4.0
(function() {

  $().ready(function() {
    module("Fizzbuzz library test");
    test("1==1", function() {
      return equal(fizzbuzz(1), 1);
    });
    test("2==2", function() {
      return equal(fizzbuzz(2), 2);
    });
    test("9==fizz", function() {
      return equal(fizzbuzz(9), "fizz");
    });
    test("10==buzz", function() {
      return equal(fizzbuzz(10), "buzz");
    });
    test("14==bizz", function() {
      return equal(fizzbuzz(14), "bizz");
    });
    test("15==fizzbuzz", function() {
      return equal(fizzbuzz(15), "fizzbuzz");
    });
    test("105==fizzbuzzbizz", function() {
      return equal(fizzbuzz(105), "fizzbuzzbizz");
    });
    return test("106==106", function() {
      return equal(fizzbuzz(106), 106);
    });
  });

}).call(this);
