// Generated by CoffeeScript 1.4.0
(function() {

  $().ready(function() {
    var container;
    container = $("#container");
    module("Bulitesztek");
    test("1===1.0", function() {
      return equal(1.1, 1);
    });
    module("Osztály szintű sayHello");
    test("Minden név kikerül", function() {
      var firstLi;
      firstLi = container.children[0];
      return equal(firstLi.innerHTML, "Hello Viktor, Ricsi");
    });
    module("Instance szintű sayHello");
    return test("Az adott név kikerül", function() {
      var secondLi;
      secondLi = container.children[1];
      return equal(secondLi.innerHTML, "Szia Ricsi!");
    });
  });

}).call(this);
