// Generated by CoffeeScript 1.4.0
(function() {
  var Name, Ricsi, Viktor;

  Name = (function() {

    Name.container = document.getElementById('container');

    Name.names = [];

    Name.sayHello = function() {
      return this.addToDom('Hello ' + this.names.join(', '));
    };

    Name.addToDom = function(txt) {
      var newLi;
      newLi = document.createElement('li');
      newLi.innerHTML = txt;
      return Name.container.appendChild(newLi);
    };

    function Name(name) {
      this.name = name;
      Name.names.push(name);
    }

    Name.prototype.sayHello = function() {
      return Name.addToDom("Szia " + this.name + '!');
    };

    return Name;

  })();

  Viktor = new Name("Viktor");

  Ricsi = new Name("Ricsi");

  Name.sayHello();

  Ricsi.sayHello();

}).call(this);
