// Generated by CoffeeScript 1.4.0
(function() {
  var Name, Ricsi, Viktor;

  Name = (function() {

    Name.names = [];

    Name.sayHello = function() {
      var name;
      return console.log('Hello ' + ((function() {
        var _i, _len, _ref, _results;
        _ref = this.names;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          name = _ref[_i];
          _results.push(name);
        }
        return _results;
      }).call(this)));
    };

    function Name(name) {
      this.name = name;
      Name.names.push(name);
    }

    Name.prototype.sayHello = function() {
      return console.log("Szia " + this.name);
    };

    return Name;

  })();

  Viktor = new Name("Viktor");

  Ricsi = new Name("Ricsi");

  Name.sayHello();

  Ricsi.sayHello();

}).call(this);
