// Generated by CoffeeScript 1.4.0
(function() {
  var Weather;

  Weather = (function() {

    function Weather() {}

    Weather.key = "";

    Weather.getLocation = function(query, callback) {
      var url;
      url = "http://autocomplete.wunderground.com/aq";
      return $.ajax({
        dataType: "jsonp",
        context: window,
        jsonp: "cb",
        data: {
          query: query,
          format: "json"
        },
        type: 'get',
        url: url,
        data: null,
        success: callback,
        crossDomain: true
      });
    };

    Weather.getWeather = function(location, callback) {
      var url;
      url = "http://api.wunderground.com/api/" + this.key + "/forecast/lang:HU/q/" + location + ".json";
      return $.ajax({
        dataType: "jsonp",
        url: url,
        data: null,
        success: callback,
        crossDomain: true
      });
    };

    return Weather;

  })();

  window.Weather = Weather;

}).call(this);
