// Generated by CoffeeScript 1.4.0
(function() {

  $().ready(function() {
    var container;
    container = $("#container");
    module("Bulitesztek");
    test("1===1.0", function() {
      return equal(1.1, 1);
    });
    module("Osztály szintű sayHello");
    return test("Minden név kikerül", function() {
      return equal(1, 1);
    });
  });

}).call(this);
